FROM python:3.7
RUN pip install --upgrade pip
RUN pip install Flask==2.1.0
RUN pip install connexion==1.1.15
RUN pip install jinja2
RUN pip install waitress
RUN pip install pandas
RUN pip install numpy
RUN pip install plotly
RUN pip install plotly-express
RUN pip install paho-mqtt

# from natorjunior/tizen-docker-cli:0.1.0
