version: '3.7'
services:
  labtvs:
    container_name: labtvs-homolog
    build:
          context: .
          dockerfile: ./Dockerfile
          args:
            APP_NAME: labstv
            ENV_NAME: homolog
    command: python app/app.py
    volumes:
      - ./:/app
    restart: unless-stopped
    ports:
      - 1130:5000
